### ISSUE TITLE
attach / detach of views does not work

### ISSUE THREAD

**Issue by tbosch** [angular/react-native-renderer#1]
Right now, we already recreate the view

**Comment by tbosch** [comment]
@scottlittle please add details here and create an issue in the react native repository that links to here.

**Comment by uber5001** [comment]
When trying to detach and re-attach a native view, the native side will fail. This is because native views get destroyed upon being removed from their parent.

Angular would benefit if these views could be re-used. Currently, the renderer just re-creates views as needed with the same set of properties and children that the destroyed view had.

When React Native supports re-use of native elements, then this renderer should be changed to use that feature.

**Comment by mlaval** [comment]
We don't have a pool of view anymore.

On top of that, the renderer optimises the interactions with React Native in order to avoid detaching / attaching when it is not needed.
