### ISSUE TITLE
high-level React components?

### ISSUE THREAD

**Issue by tomlobato** [angular/react-native-renderer#102]
Hello, great job unifying worlds!
I`m assessing react-native-renderer to use for a project and it seems very nice so far, but a key point is not clear:

> As a consequence, all the Angular 2 features are available to you: http, router, directives, dependency injection, etc. And, at the same time, all the React Native tools and features are also available.
> The only exception are the high-level React components (View, Picker, Text, Image, etc), but they all exist as ambient Angular2 components that can be used in applications.

View, Picker, Text, Image, etc are not available? What are ambient Angular2 components, is it a alternative, is it good?

**Comment by mlaval** [comment]
What it means is that you cannot directly use the React components which are available inside React Native, such as https://github.com/facebook/react-native/blob/master/Libraries/Components/View/View.js

Instead, you must use the Angular components which are available in this project, see https://github.com/angular/react-native-renderer/tree/master/src/components

They are all ambients because they can be used every where in your application, without being imported.
